server:
  port: 8083

spring:
  application:
    name: Parent-Management-System

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:parentsManagementSystem;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

    #config:
    #import: optional:configserver:http://localhost:8000


