server:
  port: 8080

spring:
  application:
    name: Api-Gateway
  cloud:
    gateway:
      routes:
        - id: STUDENT-MANAGEMENT-SYSTEM
          uri: lb://STUDENT-MANAGEMENT-SYSTEM
          predicates:
            - Path=/student/**

        - id: PARENT-MANAGEMENT-SYSTEM
          uri: lb://PARENT-MANAGEMENT-SYSTEM
          predicates:
            - Path= /Parent/**

        - id: CONFIG-SERVER
          uri: lb://CONFIG-SERVER
          predicates:
            - Path= /application/**
  config:
    import: optional:configserver:http://localhost:8000

